### ISSUE TITLE
Disk Collector only works in python2.6

### ISSUE THREAD

**Issue by sswift** [BrightcoveOS/Diamond#18]
Looks like namedtuple() was used, which breaks on 2.4 installations.

[2012-01-13 09:43:19,380] [MainThread] Failed to import module: DiskSpaceCollector. Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/diamond/server.py", line 143, in load_collectors
    mod = **import**(modname, globals(), locals(), ['*'])
  File "/usr/share/diamond/collectors/Disk/DiskSpaceCollector/DiskSpaceCollector.py", line 19
    name = 'root' if name == '_' else name
                   ^
SyntaxError: invalid syntax

[2012-01-13 09:43:19,380] [MainThread] Failed to import module: disk. Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/diamond/server.py", line 143, in load_collectors
    mod = **import**(modname, globals(), locals(), ['*'])
  File "/usr/share/diamond/collectors/Disk/disk.py", line 6, in ?
    from collections import namedtuple
ImportError: cannot import name namedtuple
