### ISSUE TITLE
rpm build on centos 6.6.

### ISSUE THREAD

**Issue by alens** [BrightcoveOS/Diamond#819]
running diamond-setup produces the following error:
Exception AttributeError: "'JCollectdCollector' object has no attribute 'listener_thread'" in <bound method JCollectdCollector.__del__ of <jcollectd.JCollectdCollector object at 0x1527910>> ignored

diamond was git cloned and make rpm version diamond-4.0.57-0.noarch.rpm 

######diamond.log ERRORS######

[2015-05-22 16:05:44,358] [MainThread] Failed to load collector LoadAverageCollector
[2015-05-22 16:05:44,359] [MainThread] Failed to initialize Collector: DiskSpaceCollector. Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/classes.py", line 203, in initialize_collector
    collector = cls(name=name, configfile=configfile, handlers=handlers)
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 168, in __init__
    logging.captureWarnings(True)
AttributeError: 'module' object has no attribute 'captureWarnings'

[2015-05-22 16:05:44,359] [MainThread] Failed to load collector DiskSpaceCollector
[2015-05-22 16:05:44,359] [MainThread] Failed to initialize Collector: DiskUsageCollector. Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/classes.py", line 203, in initialize_collector
    collector = cls(name=name, configfile=configfile, handlers=handlers)
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 168, in __init__
    logging.captureWarnings(True)
AttributeError: 'module' object has no attribute 'captureWarnings'

[2015-05-22 16:05:44,360] [MainThread] Failed to load collector DiskUsageCollector
[2015-05-22 16:05:45,362] [MainThread] Failed to initialize Collector: VMStatCollector. Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/classes.py", line 203, in initialize_collector
    collector = cls(name=name, configfile=configfile, handlers=handlers)
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 168, in __init__
    logging.captureWarnings(True)
AttributeError: 'module' object has no attribute 'captureWarnings'

[2015-05-22 16:05:45,362] [MainThread] Failed to load collector VMStatCollector
[2015-05-22 16:05:45,362] [MainThread] Failed to initialize Collector: CPUCollector. Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/classes.py", line 203, in initialize_collector
    collector = cls(name=name, configfile=configfile, handlers=handlers)
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 168, in __init__
    logging.captureWarnings(True)
AttributeError: 'module' object has no attribute 'captureWarnings'

[2015-05-22 16:05:45,362] [MainThread] Failed to load collector CPUCollector
[2015-05-22 16:05:45,363] [MainThread] Failed to initialize Collector: MemoryCollector. Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/classes.py", line 203, in initialize_collector
    collector = cls(name=name, configfile=configfile, handlers=handlers)
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 168, in __init__
    logging.captureWarnings(True)
AttributeError: 'module' object has no attribute 'captureWarnings'

**Comment by alens** [comment]
forget about it. i successfully make it with the new official github repo of diamond.. 
diamond-4.0.168-0.noarch.rpm works as it should
